### ISSUE TITLE
Style Personal Setup

### ISSUE THREAD

**Issue by Julian-Mostbauer** [Julian-Mostbauer/LinuxRicingGuide#2]
# Style Personal Setup

## Info

The new page for our personal setups needs styling.

## Who

To keep the styling consistent @Integr-0 will be assigned again. 

## Requirements
No objective requirements.

**Comment by Integr-0** [comment]
This has been implemented in #3

**Comment by Integr-0** [comment]
Closing this because it has been implemented :)
